url: 'https://mreguant.github.io'
baseurl: '/erc-enecml/'
title: 'The ENECML Project'

logo:
  mobile: "images/logo/bse_energy_400x400.jpeg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/bse_energy_400x400.jpeg"
  desktop_height: "78px"
  desktop_width: "78px"

home: 
  limit_services: 6

collections:
  projects:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
